### ISSUE TITLE
1.9 Support Checklist

### ISSUE THREAD

**Issue by dmulloy2** [dmulloy2/ProtocolLib#128]
ProtocolLib v4.0.0 is currently under heavy development.

There are development builds available on my Jenkins server: http://ci.dmulloy2.net/job/ProtocolLib/

Here's the current progress:

Pre-release:
- [x] Use packet classes instead of ids - they're apparently subject to change in the future, this can be done before it is released
- [x] Figure out why updates 403
- [X] **Release 3.6.5**
- [x] Drop support for Java 6

Post-release:
- [x] Get it to compile with 1.9
- [x] Add support for new packets
- [x] Update class names
- [x] Make sure the server & plugin start
- [x] Make sure players can join & that injection works
- [x] Update server list handling for 1.9
- [x] Fix entity tracking issues
- [x] Update the particle enum
- [x] Update data watchers and watchable objects
- [X] Create wrappers for data watcher objects and serializers
- [x] Confirm that data watcher wrappers actually work
- [x] Make sure all necessary data watcher methods have been added back
- [x] Fix cloning
- [x] Misc bug fixes
- [X] **[Release 3.7.0-BETA](https://www.spigotmc.org/resources/protocollib.1997/update?update=74595)**

Full support:
- [x] Update packet types and IDs for 1.9
- [x] Get the JavaDocs working again
- [x] Add support for 1.9 enums
- [x] Add support for 1.9 wrappers
- [x] Restore disabled tests
- [x] Update documentation
- [x] _Final bug fixes and testing_
- [x] **Release 4.0.0**
- [x] Update TinyProtocol
- [x] Update PacketWrapper

**Comment by HeroCC** [comment]
Thanks for all of your work on this plugin! It is a necessity for server owners and plugin developers alike. Good Luck with 1.9!

**Comment by tjbruce17594** [comment]
Thanks very much for this! :D

**Comment by xion87** [comment]
Thank you for the good work, hope that it will get out :)

**Comment by vintagedon** [comment]
Thank you for your awesome, continued work on this.  No spam to update, just a huge thanks for working on this!

**Comment by Sikatsu** [comment]
Thanks a lot! Appreciate your good work.

**Comment by mibby** [comment]
Very much appreciated, thanks for continued support. :) Looking forward to when watchable objects are done.

**Comment by TNTUP** [comment]
Great support to continue for 1.9! You're the king! :heart:

**Comment by KingFaris10** [comment]
@TNTUP Actually, I am. But yeah, good job and thanks dmulloy <3

**Comment by vintagedon** [comment]
I come here a couple of times a day ... waiting for that check mark next to "Release 3.7.0-BETA" :)

**Comment by dmulloy2** [comment]
@vintagedon I plan to release tomorrow barring any setbacks.

**Comment by vintagedon** [comment]
@dmulloy2 Awesome ... thanks so much for all your hard work; and for free, too.

**Comment by Litona** [comment]
Hii, I'm using an util for SignGUIs. Since the 1.9 update and the new versions, I'm sadly getting an error. As I'm just using the util, I can't really get any information out of this error. It would be really great if you could just have a look at the error and then tell me if it's caused by protocollib or by the util?
error: http://pastebin.com/Bk7GvpMp
util: https://bukkit.org/threads/sign-gui-use-the-sign-interface-to-get-user-input.177030/

**Comment by dmulloy2** [comment]
@Litona Looks to be an issue with the Util.

**Comment by Ste3et** [comment]
Hello @dmulloy2 i need your protocollib for my FurniturePlugin have you update the WrappedDataWatcher currently ?

**Comment by dmulloy2** [comment]
@Ste3et The data watcher wrapper has been updated, although there are a lot of changes in 1.9.

**Comment by edasaki** [comment]
Hello, thanks so much for the updates! Are there any plans to update TinyProtocol? I seem to be getting some errors using it in 1.9 (with code that was functional in 1.8)

**Comment by macdja38** [comment]
@edasaki see the end of the list.

**Comment by axynos** [comment]
ETA for 4.0.0?

**Comment by dmulloy2** [comment]
@axynos Hopefully soon, it's a large structural change.

**Comment by Scrayos** [comment]
Just a quick reminder: While publishing 4.0.0 keep the generation of javadoc + sources in mind.

**Comment by Sikatsu** [comment]
It seems your jenkins is unavailable right now.

**Comment by Vinc0682** [comment]
Really hoping for updated packet wrappers soon, will be able to update serveral plugins. Keep youre good work :smile:

**Comment by dmulloy2** [comment]
@Vinc0682 PacketWrapper has been updated: https://github.com/dmulloy2/PacketWrapper

**Comment by dmulloy2** [comment]
@Sikatsu Should be back up, thanks!

**Comment by Sikatsu** [comment]
Yup thanks :)

**Comment by edasaki** [comment]
Since TinyProtocol is coming up on the list of stuff to update, I was wondering if there is any chance at looking at a fix for reloading with TinyProtocol in use? I get this error when reloading with TinyProtocol: java.lang.IllegalArgumentException: Duplicate handler name: tiny-PluginName-2

I see the close() code being called, is there a step missing that's not fully removing the original handler? 

Note that when I reload twice the error does not appear on the second refresh.

**Comment by dmulloy2** [comment]
@edasaki That's odd, it should remove the handler when it closes. The only thing I can think of is that it removes the handler in the channel thread, which is only an issue when reloading. Problems like these are why I don't recommend reloading.

**Comment by edasaki** [comment]
Ah I was being silly, it only happens when I replace the plugin jar with a newer version, so the classloader can't find the old version of the class lmao. There's no issue reloading normally, only when the jar is replaced before the reload (which I know is super bad practice but I only do it on dev server anyways so whatever :P) I guess it's not a problem.

**Comment by Permanently** [comment]
Almost done... :+1:

**Comment by jflory7** [comment]
@dmulloy2++

Nice work, this is awesome to see hitting 4.0.0. :)

:confetti_ball: :fireworks: :smile: :cake: :candy:
